
# Base image
FROM node:10

# Defines /usr/src/app as a place where the application should be "built"
WORKDIR /usr/src/app

COPY package*.json ./

# update the packages and install curl into to container -> curl is istalled for testing purpose (you can delete it if wanted)
RUN apt-get update && apt-get install -y curl

RUN npm install

# Install sass to convert every single scss file into css -> so the frontend can use it
RUN npm install -g sass

COPY . .

# TODO: Add sass to css converters.

CMD [ "npm", "start" ]