
FROM node:10

# All Code will be copied into /usr/src/app -> application will also be build there
WORKDIR /usr/src/app

COPY package*.json /usr/src/app/

# First of all great all packages up and install curl (just for the sake of development -> you can delete it if you want to)
RUN apt-get update && apt-get install -y curl

RUN npm install

# Copies everything (expect things in .dockerignore)
COPY . .

# Startes the npm application
CMD [ "npm", "start" ]