
version: "3.7"

services:
    configurationService:
        build: ./ConfigurationService
        volumes:
            - ./ConfigurationService:/usr/src/app
        ports:
            - 5000:5000
    frontend:
        build: ./frontend
        volumes:
            - ./frontend:/usr/src/app
            - /usr/src/app/node_modules
        ports:
            - 3000:3000
