
version: "3.7"

services:    
    backend:
        build: ./Backend
        volumes:
            - ./Backend:/usr/src/app
        ports:
            - 5000:5000
    frontend:
        build: ./frontend
        volumes:
            - ./frontend:/urs/src/app
            - /usr/src/app/nodes_modules
        ports:
            - 3000:3000
        depends_on:
            - backend