
FROM python:3.7

# Erstellt einen Pfad, in welchem die Applikation deployed wird
WORKDIR /usr/src/app

COPY ./Requirements/requirements.txt ./

# Update von pip, falls diese benötigt wird
RUN pip install --upgrade pip

RUN pip install --no-cache-dir -r requirements.txt

# Erstelle einen Alias (schön und so)
RUN echo "alias ls='ls --color=auto'" >> ~/.bashrc

COPY . .

CMD [ "python3.7", "./main.py" ]