
FROM python:3.7

# Defines /usr/src/app as a place where the application should be "built"
WORKDIR /usr/src/app

COPY ./Requirements/requirements.txt ./

# update the packages and install curl into to container -> curl is istalled for testing purpose (you can delete it if wanted)
RUN apt-get update && apt-get install -y curl

# Update pip if needed
RUN pip install --upgrade pip

RUN pip install --no-cache-dir -r requirements.txt

# Generates an alias (you can delete it if wanted)
RUN echo "alias ls='ls --color=auto'" >> ~/.bashrc

COPY . .

CMD [ "python3.7", "./main.py" ]