
FROM python:3.7

# Erstellt einen Pfad, in welchem die Applikation deployed wird
WORKDIR /usr/src/app

COPY ./Requirements/requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD [ "python3.7", "main.py" ]