
build:
  description: @project.description@
  name: @project.name@
  version: @project.version@


appdata:
  #Change path to the location of your docker-socket
  dockerSocketURI: http://unix:/var/run/docker.sock:/v1.40/
